name: Go


on:
  push:
    branches: [ master ]
  # Allows non-contributors to run PR jobs
  pull_request_target:
    branches: [ master ]

defaults:
 run:
  shell: bash

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: "refs/pull/${{ github.event.number }}/merge"
    - uses: actions/setup-python@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - run: go install github.com/axw/gocov/gocov@latest
    - run: go install github.com/AlekSi/gocov-xml@latest

    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

